from graphics import *

def main():
    win = GraphWin("Face", 300, 300)
    win.setCoords(-150.0,-150.0,150.0,150.0)
    shape = Circle(Point(0,0), 90)
    shape.setOutline("tan")
    shape.setFill("tan")
    shape.draw(win)
    eyerwhite = Circle(Point(-35, 20), 20)
    eyerwhite.setFill('White')
    eyerwhite.setOutline('White')
    eyerwhite.draw(win)
    eyelwhite = Circle(Point(35, 20), 20)
    eyelwhite.setFill('White')
    eyelwhite.setOutline('White')
    eyelwhite.draw(win)
    eyeriris = Circle(Point(-35, 20), 15)
    eyeriris.setFill('#9e5d3f')
    eyeriris.setOutline('#9e5d3f')
    eyeriris.draw(win)
    eyeliris = Circle(Point(35, 20), 15)
    eyeliris.setFill('#9e5d3f')
    eyeliris.setOutline('White')
    eyeliris.draw(win)
    eyerpupil = Circle(Point(-35, 20), 10)
    eyerpupil.setFill('black')
    eyerpupil.setOutline('#9e5d3f')
    eyerpupil.draw(win)
    eyelpupil = Circle(Point(35, 20), 10)
    eyelpupil.setFill('black')
    eyelpupil.setOutline('#9e5d3f')
    eyelpupil.draw(win)
    mouth = Oval(Point(35,-30), Point(-35,-60))
    mouth.setFill("white")
    mouth.setOutline("white")
    mouth.draw(win)
    mouth2 = Rectangle(Point(35, -30), Point(-35, -40))
    mouth2.setFill("tan")
    mouth2.setOutline("tan")
    mouth2.draw(win)
    for i in range(20):
        p = win.getMouse()
        c = shape.getCenter()
        dx = p.getX() - c.getX()
        dy = p.getY() - c.getY()
        shape.move(dx,dy)
        eyerwhite.move(dx,dy)
        eyelwhite.move(dx,dy)
        eyeriris.move(dx,dy)
        eyeliris.move(dx,dy)
        eyerpupil.move(dx,dy)
        eyelpupil.move(dx,dy)
        mouth.move(dx,dy)
        mouth2.move(dx,dy)
    win.getMouse()
    win.close()

main()
