#!/bin/bash
#Morgan Precanico
#2018-Oct-1

MAC Address Tool
read -p "Which tool would you like to use?
1. Hexadecimal to Binary
2. OUI List
> " tool

case $tool in
2.)
read -p "Which company OUI would you like to view? [HP, ASUS]" oui
;;
esac
#HEX Variables
$0="$0b"
$1="$1b"
$2="$2b"
$3="$3b"
$4="$4b"
$5="$5b"
$6="$6b"
$7="$7b"
$8="$8b"
$9="$9b"
$10="$ab"
$11="$bb"
$12="$cb"
$13="$db"
$14="$eb"
$15="$fb"

#MAC to Binary
$0b="0000"
$1b="0001"
$2b="0010"
$3b="0011"
$4b="0100"
$5b="0101"
$6b="0110"
$7b="0111"
$8b="1000"
$9b="1001"
$ab="1010"
$bb="1011"
$cb="1100"
$db="1101"
$eb="1110"
$fb="1111"

#List of OUIs (Orginizationally Unique Identifiers)

case $oui in

ASUS)
cat Documents/lib/MAC/ASUSTek.txt
read -p "Any Additions? [#) ##:##:##]" ASUSoui
cat $ASUSoui >> Documents/lib/MAC/ASUSTek.txt 
;;

HP)
cat Documents/lib/MAC/Hewlett.txt
;;

1c:98:ec)
company="Hewlett Packard Enterprise"
;;

cc:3a:61)
company="Samsung Electro Mechanics"
;;






esac





#Details of MAC Address
echo "MAC Address:$addr"
echo "Company:$company"
